-- Seed staff agents
-- IMPORTANT: This migration is for reference only
-- Do NOT run this migration - it will fail because staff_agents.id is required
-- 
-- Instead, follow these steps:
-- 1. Create auth users in Supabase dashboard (Authentication > Users)
-- 2. Copy their UUIDs
-- 3. Run the SQL in migration 007_populate_staff_agents.sql with the actual UUIDs
--
-- This file is kept for documentation purposes only

-- Example of what would be inserted (do not run):
-- INSERT INTO staff_agents (id, email, name, type, created_at, updated_at)
-- VALUES
--   ('AUTH_USER_UUID_1', 'registration@carflex.com', 'Registration Agent', 'REGISTRATION_AGENT', NOW(), NOW()),
--   ('AUTH_USER_UUID_2', 'gate@carflex.com', 'Gate Verification Agent', 'GATE_VERIFICATION_AGENT', NOW(), NOW()),
--   ('AUTH_USER_UUID_3', 'ground@carflex.com', 'Ground Verification Agent', 'GROUND_VERIFICATION_AGENT', NOW(), NOW()),
--   ('AUTH_USER_UUID_4', 'exit@carflex.com', 'Exit Command Agent', 'EXIT_COMMAND_AGENT', NOW(), NOW())
-- ON CONFLICT (id) DO NOTHING;
